name: Update Publish Date

on:
  push:
    branches:
      - master

jobs:
  update:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update timestamp in index.html
        run: |
          ts=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          sed -i -E "s/(<span id=\"publish-timestamp\">)[^<]+/\1${ts}/" index.html
      - name: Commit and push changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add index.html
            git commit -m "Update publish timestamp"
            git push
          fi
